# Generated by Django 5.1.1 on 2025-09-21 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0005_alter_achievement_tier_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="required_quest_completions",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
