from setuptools import find_packages, setup

setup(
    name="life_dashboard",
    version="0.1",
    author="Nigel",
    author_email="nigel@example.com",
    description="A personal dashboard for tracking life stats, quests, and habits.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/life_dashboard",
    license="MIT",
    packages=find_packages(),
    install_requires=[
        "Django==5.0.2",
        "python-dotenv==1.0.1",
        "django-crispy-forms==2.1",
        "crispy-bootstrap5==2024.2",
        "Pillow==10.3.0",
        "django-allauth==0.61.1",
        "django-environ==0.11.2",
        "whitenoise==6.6.0",
        "gunicorn==23.0.0",
        "psycopg2-binary==2.9.9",
        "pytest==8.0.2",
        "pytest-django==4.8.0",
        "selenium==4.18.1",
        "webdriver-manager==4.0.1",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: End Users/Desktop",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Framework :: Django",
        "Framework :: Django :: 5.0",
    ],
    python_requires=">=3.8",
)
