# Generated by Django 5.1.1 on 2025-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0002_alter_habit_options_alter_habitcompletion_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="quest",
            name="experience_reward",
        ),
        migrations.RemoveField(
            model_name="quest",
            name="quest_type",
        ),
        migrations.RemoveField(
            model_name="quest",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="quest",
            name="status",
        ),
        migrations.AddField(
            model_name="quest",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
