# Generated by Django 5.1.1 on 2025-06-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "quests",
            "0003_remove_quest_due_date_remove_quest_experience_reward_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quest",
            name="experience_reward",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="quest",
            name="quest_type",
            field=models.CharField(
                choices=[
                    ("main", "Main Quest"),
                    ("side", "Side Quest"),
                    ("daily", "Daily Quest"),
                ],
                default="main",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quest",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
