# Generated by Django 5.1.1 on 2025-06-10 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0004_quest_due_date_quest_experience_reward_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habitcompletion",
            name="completed_at",
        ),
        migrations.AddField(
            model_name="habitcompletion",
            name="count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="habitcompletion",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="habit",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="habitcompletion",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completions",
                to="quests.habit",
            ),
        ),
    ]
