# Generated by Django 5.1.1 on 2025-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0006_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="experience_reward",
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
