# Generated by Django 5.1.1 on 2025-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0007_habit_experience_reward_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitcompletion",
            name="experience_gained",
            field=models.IntegerField(default=0),
        ),
    ]
