# Generated by Django 5.1.1 on 2025-06-10 19:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0008_habitcompletion_experience_gained"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitcompletion",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
