# Generated by Django 5.1.1 on 2025-06-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0009_alter_habitcompletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
