# Generated by Django 5.1.1 on 2025-09-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0010_quest_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("paused", "Paused"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
