# Generated by Django 5.1.1 on 2025-09-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0011_alter_quest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("custom", "Custom"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("legendary", "Legendary"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="quest_type",
            field=models.CharField(
                choices=[
                    ("life_goal", "Life Goal"),
                    ("annual_goal", "Annual Goal"),
                    ("main", "Main Quest"),
                    ("side", "Side Quest"),
                    ("weekly", "Weekly Quest"),
                    ("daily", "Daily Quest"),
                ],
                default="main",
                max_length=15,
            ),
        ),
    ]
