# Generated by Django 5.1.1 on 2025-09-20 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0012_add_missing_enum_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitcompletion",
            name="count",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
