# Generated by Django 5.1.1 on 2025-09-20 18:17

from django.db import migrations


def backfill_experience(apps, schema_editor):
    HabitCompletion = apps.get_model("quests", "HabitCompletion")
    Habit = apps.get_model("quests", "Habit")

    habit_rewards = {
        habit.pk: habit.experience_reward for habit in Habit.objects.all()
    }

    for completion in HabitCompletion.objects.all():
        reward = habit_rewards.get(completion.habit_id, 0)
        count = max(completion.count, 0)
        experience = reward * count
        if completion.experience_gained != experience:
            completion.experience_gained = experience
            completion.save(update_fields=["experience_gained"])


def noop_reverse(apps, schema_editor):
    """No-op reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0013_alter_habitcompletion_count"),
    ]

    operations = [
        migrations.RunPython(backfill_experience, noop_reverse),
    ]
