# Generated by Django 5.1.1 on 2025-06-10 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_userprofile_email_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="level",
        ),
        migrations.DeleteModel(
            name="Stats",
        ),
    ]
