# Generated by Django 5.1.1 on 2025-06-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_remove_userprofile_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="experience_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
