# Generated by Django 5.1.1 on 2025-06-17 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=1)),
                ("experience", models.PositiveIntegerField(default=0)),
                ("health", models.IntegerField(default=100)),
                ("energy", models.IntegerField(default=100)),
                ("strength", models.IntegerField(default=10)),
                ("agility", models.IntegerField(default=8)),
                ("endurance", models.IntegerField(default=7)),
                ("intelligence", models.IntegerField(default=5)),
                ("charisma", models.IntegerField(default=5)),
                ("wisdom", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stats",
                "verbose_name_plural": "Stats",
            },
        ),
    ]
