# Generated by Django 5.1.1 on 2025-09-20 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeStatCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Life Stat Category",
                "verbose_name_plural": "Life Stat Categories",
                "db_table": "stats_lifestatcategory",
            },
        ),
        migrations.AlterModelOptions(
            name="stats",
            options={
                "verbose_name": "Stats (Legacy)",
                "verbose_name_plural": "Stats (Legacy)",
            },
        ),
        migrations.CreateModel(
            name="CoreStatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strength", models.IntegerField(default=10)),
                ("endurance", models.IntegerField(default=10)),
                ("agility", models.IntegerField(default=10)),
                ("intelligence", models.IntegerField(default=10)),
                ("wisdom", models.IntegerField(default=10)),
                ("charisma", models.IntegerField(default=10)),
                ("experience_points", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidated_core_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Core Stat",
                "verbose_name_plural": "Core Stats",
                "db_table": "stats_corestat",
            },
        ),
        migrations.CreateModel(
            name="LifeStatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidated_life_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Life Stat",
                "verbose_name_plural": "Life Stats",
                "db_table": "stats_lifestat",
                "unique_together": {("user", "category", "name")},
            },
        ),
        migrations.CreateModel(
            name="StatHistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_type", models.CharField(max_length=20)),
                ("stat_name", models.CharField(max_length=100)),
                ("old_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("change_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("change_reason", models.CharField(blank=True, max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stat History",
                "verbose_name_plural": "Stat Histories",
                "db_table": "stats_stathistory",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "stat_type", "stat_name"],
                        name="stats_stath_user_id_85d603_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="stats_stath_user_id_a2b4e9_idx",
                    ),
                ],
            },
        ),
    ]
