# Generated by Django 5.1.1 on 2025-09-20 18:14

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0004_remove_old_core_stats_references"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="corestatmodel",
            name="experience_points",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="corestatmodel",
            name="level",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="stats",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__gte", 1)), name="stats_level_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="stats",
            constraint=models.CheckConstraint(
                condition=models.Q(("experience__gte", 0)),
                name="stats_experience_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="stats",
            constraint=models.CheckConstraint(
                condition=models.Q(("health__gte", 0)), name="stats_health_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stats",
            constraint=models.CheckConstraint(
                condition=models.Q(("energy__gte", 0)), name="stats_energy_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stats",
            constraint=models.CheckConstraint(
                condition=models.Q(("strength__gte", 0)), name="stats_strength_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stats",
            constraint=models.CheckConstraint(
                condition=models.Q(("agility__gte", 0)), name="stats_agility_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stats",
            constraint=models.CheckConstraint(
                condition=models.Q(("endurance__gte", 0)), name="stats_endurance_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stats",
            constraint=models.CheckConstraint(
                condition=models.Q(("intelligence__gte", 0)),
                name="stats_intelligence_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="stats",
            constraint=models.CheckConstraint(
                condition=models.Q(("charisma__gte", 0)), name="stats_charisma_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stats",
            constraint=models.CheckConstraint(
                condition=models.Q(("wisdom__gte", 0)), name="stats_wisdom_gte_0"
            ),
        ),
    ]
