# Generated by Django 5.1.2 on 2025-04-01 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeStatCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Life Stat Category",
                "verbose_name_plural": "Life Stat Categories",
            },
        ),
        migrations.CreateModel(
            name="LifeStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.FloatField(default=0)),
                ("target", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="life_stats.lifestatcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Life Stat",
                "verbose_name_plural": "Life Stats",
                "unique_together": {("user", "category", "name")},
            },
        ),
    ]
