name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev libjpeg-dev libpng-dev redis-server

      - name: Start Redis
        run: |
          sudo systemctl start redis-server
          sudo systemctl status redis-server

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          # Install main dependencies first
          pip install django>=5.1.1 django-crispy-forms crispy-bootstrap5 celery redis python-dotenv pydantic
          # Then install dev dependencies
          pip install -r requirements-dev.txt || pip install pytest pytest-django pytest-cov import-linter mypy django-stubs ruff pre-commit behave selenium

      - name: Check Django setup
        run: python manage.py check
        env:
          DJANGO_SETTINGS_MODULE: life_dashboard.life_dashboard.settings

      - name: Run Migrations
        run: python manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: life_dashboard.life_dashboard.settings

      - name: Run tests
        run: pytest
        continue-on-error: ${{ github.ref != 'refs/heads/main' }}
        env:
          DJANGO_SETTINGS_MODULE: life_dashboard.life_dashboard.test_settings

      - name: Run Ruff (Linting and Formatting)
        run: |
          ruff check .
          ruff format . --check

      - name: Run Type Checking
        run: make type-check-strict

      - name: Check Dependencies
        run: make check-deps

      - name: Run Architecture Checks
        run: make check-architecture
        env:
          IMPORT_LINTER_STRICT: "1"
